image: node:8.10.0

cache:
  paths:
    - node_modules/

stages:
  - pre_deploy
  - deploy_production

Install:
  stage: pre_deploy
  script:
    - npm install

Lint:
  stage: pre_deploy
  script:
    - npm run lint

UnitTest:
  stage: pre_deploy
  script:
    - npm run test

Production:
  image: ruby:latest
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=binar-express --api-key=$HEROKU_API_KEY